// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

const { defineConfig } = require("prisma/config");
require("dotenv").config();

module.exports = defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    adapter: "sqlite",
    url: process.env.DATABASE_URL || "file:./dev.db",
  },
});



